[project]
name = "project-template"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "numpy>=1.20.0",
    "pandas>=2.3.3",
    "transformers>=4.57.3",
    "wandb>=0.23.1",
    "diffusers>=0.33.1",
    "torch==2.5.1",
    "timm==0.9.6",
    "httpx==0.20.0",
    "gputil>=1.4.0",
    "omegaconf>=2.3.0",
    "einops>=0.8.1",
    "onnxruntime>=1.23.2",
    "accelerate>=1.12.0",
    "trustmark>=0.9.0",
    "datasets>=4.4.1",
    "scipy>=1.16.3",
    "scikit-learn>=1.8.0",
    "matplotlib>=3.10.8",
    "sentencepiece>=0.2.1",
    "opencv-python>=4.11.0.86",
    "imageio>=2.37.2",
    "sentencepiece>=0.2.1",
    "opencv-python>=4.11.0.86",
    "imageio>=2.37.2",
    "pytorch-lightning>=2.6.0",
    "open-clip-torch>=2.32.0",
    "xformers>=0.0.29.post1",
    "flash-attn",
    "typed-argument-parser>=1.11.0",
    "colorama>=0.4.6",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = ["pre-commit>=4.4.0", "ruff>=0.14.6"]

[tool.mypy]
warn_unused_configs = true
ignore_missing_imports = true
warn_unused_ignores = false
show_error_codes = true
check_untyped_defs = true
no_implicit_optional = true
explicit_package_bases = true

[tool.ruff]
unsafe-fixes = true
exclude = [".venv"]
extend-include = ["*.ipynb"]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
preview = true
explicit-preview-rules = true
select = [
    # Default rules
    "E",     # pycodestyle errors
    "F",     # Pyflakes
    "C4",    # flake8-comprehensions
    "C90",   # mccabe complex structure
    "D",     # pydocstyle
    "I",     # isort
    "PT",    # flake8-pytest-style
    "PL",    # Pylint
    "SIM",   # flake8-simplify
    "UP",    # pyupgrade
    "W",     # pycodestyle warnings
    "S",     # flake8-bandit
    "ANN",   # flake8-annotations
    "B",     # flake8-bugbear
    "NPY",   # NumPy-specific rules
    "UP045",
]
extend-select = [
    "RUF022",  # unsorted-dunder-all
    "PLR6301", # no-self-use
]
ignore = [
    "B024",
    "B028",    # no-explicit-stacklevel
    "B904",
    "C901",    # complex-structure
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D415",
    "D200",
    "D205",
    "D212",
    "E722",
    "ANN002",
    "ANN003",
    "ANN204",  # dynamically typed expressions
    "ANN401",
    "PLR0913",
    "PLR2004", # magic value used in comparison
    "PT028",   # test function parameter has default argument
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",
    "S105",
    "S106",
    "ANN001",
    "ANN201",
    "PLR6301",
    "PT011",
]


[tool.ruff.lint.pylint]
max-locals = 20

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 120

[tool.bandit]
exclude_dirs = [".venv"]

[tool.uv.sources]
flash-attn = { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu12torch2.5cxx11abiFALSE-cp312-cp312-linux_x86_64.whl" }
